"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var FloorImage = String.raw(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n                                                |>>>\n                                                |\n                                            _  _|_  _\n                                           |;|_|;|_|;|\n                                           \\.    .  /\n                                            \\:  .  /\n                                             ||:   |\n                                             ||:.  |\n                                             ||:  .|\n                                             ||:   |       ,/\n                                             ||: , |            /\u00B0                                             ||:   |\n                                             ||: . |\n              __                            _||_   |\n     ____--'~    '--~~__            __ ----~    ~'---,              ___\n-~--~                   ~---__ ,--~'                  ~~----_____-~'   '~----~~\n\n"], ["\n                                                |>>>\n                                                |\n                                            _  _|_  _\n                                           |;|_|;|_|;|\n                                           \\\\.    .  /\n                                            \\\\:  .  /\n                                             ||:   |\n                                             ||:.  |\n                                             ||:  .|\n                                             ||:   |       \\,/\n                                             ||: , |            /\u00B0\\\n                                             ||:   |\n                                             ||: . |\n              __                            _||_   |\n     ____--'~    '--~~__            __ ----~    ~'---,              ___\n-~--~                   ~---__ ,--~'                  ~~----_____-~'   '~----~~\n\n"])));
exports.default = FloorImage;
var templateObject_1;
